### PR TITLE
(WIP) F319 new sorting and pagination for projects

### PR DESCRIPTION
**Pull request by mateodaza**
This one depends on the impact graph to be synced with this [PR](https://github.com/Giveth/impact-graph/pull/167) currently working with https://dev.serve.giveth.io/graphql

I miscalculated and couldn't get everything done for today  😞  please while I'm gone can someone keep working on this @RamRamez @mohammadranjbarz @MohammadPCh @CarlosQ96 I'd really really appreciate it

Adding pagination, filtering and searching is still missing but the integration began on a couple of pages.

Left some examples of its use on topProjects in the landing page and the /projects route, you'll easily notice it. I was going to base on this to make the changes, feel free to check it out!
https://www.apollographql.com/docs/react/pagination/core-api/

Here's also a snippet with everything we need to do all
- orderBy.field for the filtering
- searchTerm for the searching

carbon (1)

These are the enums
carbon (2)

kudos to @CarlosQ96 for the amazing work and guys thanks a lot, I'll be back soon with all the energy to support the launch

image

### CODE REVIEW

**Comment by RamRamez** [comment]
@mohammadranjbarz @CarlosQ96 It seems there are some problems with the GraphQL in "FETCH_ALL_PROJECTS" queries:

1. when sorting by "Verified", it returns not verified! It should return empty array if there is no verified.
2. we fetch verified projects from Trace in front-end so how we gonna handle that with GQL queries?
3. totalHearts is always null so sorting by "totalHearts" is not working
4. I can't check donation queries because there are no donations for projects in this DB
5. Recently added returns empty array, which projects does it return?
6. "oldProjects" and "recentlyAdded" is a little confusing. I think we can replace them by "creationDate" and allowing user to sort "DESC" and "ASC"

**Comment by CarlosQ96** [comment]
@RamRamez Regarding the list:
1. I'll upload a hotfix here to my branch and develop for Verified.
2. This will be fixed in another issue that Mohammad is working on I think. We can discuss tomorrow.
3. Hmm which impact-graph branch are you testing with? I renamed the totalHearts to Reactions and used a completely custom query, and not the totalHearts column. Try using the Reactions Enum value.
4. There should be one or two projects with donations, I can help here.

Last two:
5.  Mateo told me recently added means projects made this month, so probably it's empty because there are none in dev.
6. Old Projects means created 1 month+.  However I agree with you, if we decide to keep it by creationDate DESC and ASC it would simplify things.

**Comment by mohammadranjbarz** [comment]
@RamRamez  @CarlosQ96 
1. About the first one I don't agree, we are sorting by 'verified' not filtering, so we should show the non verified projects, for example if none of projects doesn't have hearts, and we sort by hearts we should not show any project?
I believe not.
2. Carlos is right, our project are IO first so for any verified campaign we should have a related projects for verified campaigns, so you should not call trace.giveth.io for getting campaigns anymore, but consider if a project has `isTraceable:true` then you should consider it's traceable, but also user can `heart` it , 
if you had more questions please ask from me, because I working on this issue right now

**Review by mohammadranjbarz — APPROVED** [review]
Thanks @RamRamez  Seems good to me

**Pull request merged**
